server:
  port: 9081
  servlet:
    context-path: /myfavorites/api

spring:
  application:
    name: myfavorites-account
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: ${server.servlet.context-path}/actuator/health
        health-check-interval: 15s
  datasource:
    url: jdbc:mysql://localhost:3306/myfavorites?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowPublicKeyRetrieval=true
    username: Your username
    password: Your password
    schema: classpath:database/schema.sql
    data: classpath:database/data.sql
    sql-script-encoding: UTF-8
    initialization-mode: always
    jpa:
      show-sql: true
  redis:
    host: localhost
    port: 6379
    password: Your password
  mail:
    host: Your SMTP server like smtp.126.com
    username: Your Email Address
    password: Your password
    default-encoding: UTF-8
  jackson:
    default-property-inclusion: NON_NULL

custom-params:
  verify-code-valid-seconds: 300 # 5 minutes
  verify-code-retry-max: 5 # 5 times/day
  web-client-id: MyFavoritesWeb
  web-client-secret: Your Secret
  web-client-scopes: User-WEB
  web-access-validity-seconds: 900 # 15 minutes
  web-refresh-validity-seconds: 432000 # 5 days
  mobile-client-id: MyFavoritesMobile
  mobile-client-secret: Your Secret
  mobile-client-scopes: User-MOBILE
  mobile-access-validity-seconds: 900 # 15 minutes
  mobile-refresh-validity-seconds: 259200 # 3 days
  visitor-client-id: MyFavoritesVisitor
  visitor-client-secret: Your Secret
  visitor-client-scopes: Visitor-Restricted
  visitor-access-validity-seconds: 600 # 10 minutes
  visitor-refresh-validity-seconds: 0 # not allowed
  server-internal-id: MyFavoritesServer
  server-internal-secret: Your Secret